print("Casting adalah mengubah satu tipe data ke tipe lain")

print("====================INTEGER====================")
print("Mengubah data integer ke tipe data lain")
data_int = 1
data_int2 = 0
print("data_int = ", data_int, "type =", type(data_int))
data_float  = float(data_int) 
data_string = str(data_int) 
data_bool   = bool(data_int) 
data_bool2  = bool(data_int2)
print("1. data float =", data_float,"-> type data =", type(data_float)) 
print("2. data string =", data_string,"-> type data =", type(data_string)) 
print("3.a. data bool =", data_bool,"-> type data =", type(data_bool)) 
print("3.b. data bool =", data_bool2,"-> type data =", type(data_bool2))
print("CATATAN")
print("Int ke float -> nilai data integer akan ditambah .0")
print("Int ke string -> nilai akan diubah menjadi text angka, bukan nilai angka")
print("Int ke bool -> jika nilai lebih dari 0 maka akan menghasilkan true, termasuk nilai negatif")
print("\n")
print("====================FLOAT====================")
print("Mengubah data FLOAT ke tipe data lain")
data_float = 10.2
data_float2 = 8.9
print("data_float = ", data_float, "type =", type(data_float))
print("data_float2 = ", data_float2, "type =", type(data_float2))
data_int  = int(data_float) 
data_int2   = int(data_float2)
data_string = str(data_float) 
data_bool   = bool(data_float) 
print("1.a. data int =", data_int,"-> type data =", type(data_int))
print("1.b. data int =", data_int2, "-> type", type(data_int2)) 
print("2. data string =", data_string,"-> type data =", type(data_string)) 
print("3. data bool =", data_bool,"-> type data =", type(data_bool)) 
print("CATATAN")
print("Float ke Int -> nilai di belakang koma akan hilang dibulatkan ke bawah")
print("Float ke str -> nilai akan berubah menjadi teks")
print("float ke bool -> nilai >0 akan menjadi True, 0 menjadi false")
print("\n")
print("====================STRING====================")
print("Mengubah data STRING ke tipe data lain")
data_string = "empat"
data_string2 = "10"
print("data_string = ", data_string, "type =", type(data_string))
print("data_string2 = ", data_string2, "type =", type(data_string2))
#data_int  = int(data_string) 
#data_float = float(data_string) 
#data_bool   = bool(data_string) 
#print("1. data int =", data_int,"-> type data =", type(data_int))
#print("2. data string =", data_float,"-> type data =", type(data_float)) 
#print("3. data bool =", data_bool,"-> type data =", type(data_bool)) 
print("CATATAN")
print("string ke Int -> jika string berupa angka misal 10, maka menjadi 10 Error")
print("string ke float -> selain huruf akan menjadi Error")
print("string ke bool -> Jika kosong maka menjadi false, jika angka satu menjadi true, huruf Error")
print("\n")
print("====================BOOL====================")
print("Mengubah data BOOL ke tipe data lain")
data_bool = True
data_bool2 = False
print("data_bool = ", data_bool, "type =", type(data_bool))
print("data_bool2 = ", data_bool2, "type =", type(data_bool2))
data_int  = int(data_bool) 
data_int2 = int(data_bool2)
data_string = str(data_bool) 
data_float   = float(data_bool)
data_float2  = float(data_bool2)
print("1. data int =", data_int,"-> type data =", type(data_int)) 
print("1.b. data int =", data_int2, "-> type data =", type(data_int2))
print("2. data string =", data_string,"-> type data =", type(data_string)) 
print("3.a. data float =", data_float,"-> type data =", type(data_float))
print("3.b. data float2 =", data_float2,"-> type data =", type(data_float2)) 
print("CATATAN")
print("Bool ke Int -> true menjadi 1, false menjadi 0")
print("Bool ke str -> nilai akan berubah menjadi teks true/false")
print("Bool ke float -> true menjadi 1.0, false menjadi 0.0")